name: Test AWS access
on:
  push:
    branches:
      - master

jobs:
  test-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Try AWS CLI
        run: |
          which aws
          aws s3 help | cat
      - name: Test Docker
        run: |
          which docker
          docker image ls --all