name: Test AWS access
on:
  push:
    branches:
      - master

jobs:
  test-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/stepan/${{ github.event.repository.name }}-${{ github.ref_name }}:latest

      - name: Build docker image - 2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/stepan/${{ github.event.repository.name }}-${{ github.ref_name }}:latest

      - name: Publish On-Premise Crawler
        if: github.ref_name == 'master'
        run: |
          docker image ls --all
          export GHCR_TAG="ghcr.io/stepan/${{ github.event.repository.name }}-${{ github.ref_name }}:latest"
          export ON_PREMISE_TAG="${{ github.event.repository.name }}-${{ github.ref_name }}:latest"
          export IMAGE_TAR="${{ github.event.repository.name }}-${{ github.ref_name }}.tar"
          
          docker tag "$GHCR_TAG" "$ON_PREMISE_TAG"
          docker save "$ON_PREMISE_TAG" -o "$IMAGE_TAR"
          ls -l