name: Canary Release
on:
  pull_request:
    types: [ opened, synchronize, labeled ]

jobs:
  release:
    runs-on: ubuntu-latest
    if: (github.head_ref != 'master' && github.head_ref != 'staging' && github.head_ref != 'beta') && ((github.event.action == 'labeled' && github.event.label.name == 'canary') || contains(github.event.pull_request.labels.*.name, 'canary'))

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: "Setup NodeJS"
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: "Setup NPM"
        run: |
          npm ci
          npx lerna bootstrap -- --force-local
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: "Make Canary Release"
        run: |
          npm run release:canary
