name: Publish
on:
  push:
    branches:
      - dev
      - staging
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          # This is required to bypass branch protection rules by GitHub actions.
          # See https://stackoverflow.com/a/63733988
          persist-credentials: false
          fetch-depth: 0

      - name: "Setup NPM"
        run: |
          npm ci
          npx lerna bootstrap -- --force-local
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: "Version and Publish"
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.CI_TOKEN }}@github.com/$GITHUB_REPOSITORY

          if [ ${{ github.ref_name }} = dev ]; then
            npx lerna version --no-changelog --conventional-commits --conventional-prerelease --include-merged-tags --no-push --preid alpha --yes
            npx lerna publish from-package --dist-tag dev --yes
          elif [ ${{ github.ref_name }} = staging ]; then
            npx lerna version --no-changelog --conventional-commits --conventional-prerelease --include-merged-tags --no-push --preid beta --yes
            npx lerna publish from-package --dist-tag next --yes
          elif [ ${{ github.ref_name }} = master ]; then 
            npx lerna version --no-changelog --conventional-commits --conventional-graduate --yes
            npx lerna publish from-package --yes
          fi

      - name: "Auto-merge master->staging"
        uses: actions/github-script@v6
        if: github.ref_name == 'master'
        with:
          script: |
            // See: https://octokit.github.io/rest.js/v19#repos-merge
            // See: https://github.com/actions/github-script
            github.rest.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: "staging",
              head: "master",
              commit_message: "Auto-merge master into staging"
            });