name: Publish
on:
  push:
    branches:
      - dev
      - staging
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // Get a list of all issues created by the PR opener
            // See: https://octokit.github.io/rest.js/#pagination
            const response = await github.rest.repos.compareCommitsWithBasehead({
              owner: context.repo.owner,
              repo: context.repo.repo,
              basehead: "staging...master",
            });
            
            console.log(JSON.stringify(response, null, 2));
            
            console.log(JSON.stringify(context, null, 2))
            console.log(JSON.stringify(github, null, 2))
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Setup NPM"
        run: |
          npm ci
          npx lerna bootstrap -- --force-local
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: "Version and Publish"
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY

          if [ ${{ github.ref_name }} = dev ]; then
            npx lerna version --no-changelog --conventional-commits --conventional-prerelease --no-push --preid alpha --yes
            npx lerna publish from-package --dist-tag dev --yes
          elif [ ${{ github.ref_name }} = staging ]; then
            npx lerna version --no-changelog --conventional-commits --conventional-prerelease --include-merged-tags --no-push --preid beta --yes
            npx lerna publish from-package --dist-tag next --yes
          elif [ ${{ github.ref_name }} = master ]; then 
            npx lerna version --no-changelog --conventional-commits --conventional-graduate --yes
            npx lerna publish from-package --yes
          fi

      - name: "Auto-merge master->staging"
        uses: actions/github-script@v6
        if: github.ref_name == 'master'
        with:
          script: |
            // See: https://octokit.github.io/rest.js/v19#repos-merge
            // See: https://github.com/actions/github-script
            github.rest.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: "staging",
              head: "master",
              commit_message: "Auto-merge master into staging"
            });