name: Publish Master [PR]
on:
  pull_request:
    types: [ closed ]
    branches:
      - master

concurrency: publish-master
jobs:
  publish-master:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: |
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.ref_protected = ${{ github.ref_protected }}"
          echo "github.ref_type = ${{ github.ref_type }}"
          echo "github.head_ref = ${{ github.head_ref }}"
          echo "github.base_ref = ${{ github.base_ref }}"
          echo "github.sha = ${{ github.sha }}"
          git rev-list -n 1 "origin/${{ github.head_ref }}"
          git rev-list -n 1 "origin/${{ github.base_ref }}"