name: Refresh Sanity Check
on:
  pull_request:
    types: [ closed ]
    branches:
      - staging

jobs:
  refresh:
    if: github.event.pull_request.merged
    uses: ./.github/workflows/sanity_check.yaml
