name: Merge Sanity
on:
  pull_request:
    types: [closed]
    branches:
      - staging

jobs:
  publish_prerelease:
    name: "Publish next versions"
    runs-on: ubuntu-latest
    outputs:
      test-a: ${{ steps.changes.outputs.a }}
      test-b: ${{ steps.changes.outputs.b }}
      test-c: ${{ steps.changes.outputs.c }}
      test-parent: ${{ steps.changes.outputs.parent }}
      status: ${{ job.status }}
    steps:
      - name: "Check Merged into Staging"
        uses: actions/github-script@v6
        if: github.event.pull_request.merged == false
        with:
          # See actions/github-script@v6: https://github.com/actions/github-script#actionsgithub-script
          # See compareCommitsWithBasehead: https://octokit.github.io/rest.js/v19#repos-compare-commits-with-basehead
          # See @actions/core: https://github.com/actions/toolkit/tree/main/packages/core#exit-codes
          script: |
            core.setFailed("Feature-branch must be merged into 'staging' before merging into 'master'.");

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          # This is required to bypass branch protection rules by GitHub actions.
          # See https://stackoverflow.com/a/63733988
          persist-credentials: false
          fetch-depth: 0

      - name: "Setup NPM"
        run: |
          npm ci
          npx lerna bootstrap -- --force-local
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: "Version and Publish"
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.CI_TOKEN }}@github.com/$GITHUB_REPOSITORY

          npm run release:staging

      - name: "Select Packages"
        uses: actions/github-script@v6
        id: changes
        with:
          script: |
            // Get changed paths
            const execSync = require('child_process').execSync;
            const changes = execSync('git diff --name-only origin/master', {encoding: 'utf-8'}).split('\n')

            console.log(JSON.stringify(changes, null, 2));

            // Set output flags
            core.setOutput('a', changes.includes('packages/a/package.json'));
            core.setOutput('b', changes.includes('packages/b/package.json'));
            core.setOutput('c', changes.includes('packages/c/package.json'));
            core.setOutput('parent', changes.includes('packages/parent/package.json'));

  test-a:
    name: "Test Library A"
    runs-on: ubuntu-latest
    needs: publish_prerelease
    if: needs.publish_prerelease.outputs.test-a == 'true'
    outputs:
      status: ${{ job.status }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Run Tests"
        run: |
          npm ci
          npx lerna bootstrap -- --force-local
          cd packages/a
          npm run test

  test-b:
    name: "Test Library B"
    runs-on: ubuntu-latest
    needs: publish_prerelease
    if: needs.publish_prerelease.outputs.test-b == 'true'
    outputs:
      status: ${{ job.status }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Run Tests"
        run: |
          npm ci
          npx lerna bootstrap -- --force-local
          cd packages/b
          npm run test

  checkpoint-1:
    name: "Check Point 1"
    runs-on: ubuntu-latest
    needs:
      - publish_prerelease
      - test-a
      - test-b
    if: ${{ always() }}
    outputs:
      test-c: ${{ needs.publish_prerelease.outputs.test-c }}
      test-parent: ${{ needs.publish_prerelease.outputs.test-parent }}
      status: ${{ job.status }}
    steps:
      - name: Check Test Results
        uses: actions/github-script@v6
        with:
          script: |
            const statuses = {
              "a": "${{needs.test-a.outputs.status}}",
              "b": "${{needs.test-b.outputs.status}}",
            };
            console.log("Collected Test Results:");
            console.log(JSON.stringify(statuses, null, 2));

            if(Object.values(statuses).some(status => status === "failure")) {
              core.setFailed("Some tests failed.");
            }

  test-c:
    name: "Test Library C"
    runs-on: ubuntu-latest
    needs:
      - checkpoint-1
    if: always() && needs.checkpoint-1.outputs.test-c == 'true'
    outputs:
      status: ${{ job.status }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Run Tests"
        run: |
          echo $${{ needs.checkpoint-1.outputs.test-c }} ${{ needs.checkpoint-1.outputs.test-c == 'true' }}
          npm ci
          npx lerna bootstrap -- --force-local
          cd packages/c
          npm run test

  checkpoint-2:
    name: "Check Point 2"
    runs-on: ubuntu-latest
    needs:
      - checkpoint-1
      - test-c
    if: ${{ always() }}
    outputs:
      test-parent: ${{ needs.checkpoint-1.outputs.test-parent }}
      status: ${{ job.status }}
    steps:
      - name: Check Test Results
        uses: actions/github-script@v6
        with:
          script: |
            const statuses = {
              "Check Point 1": "${{needs.checkpoint-1.outputs.status}}",
              "c": "${{needs.test-c.outputs.status}}",
            };
            console.log("Collected Test Results:");
            console.log(JSON.stringify(statuses, null, 2));

            if(Object.values(statuses).some(status => status === "failure")) {
              core.setFailed("Some MABL tests failed.");
            }

  test-parent:
    name: "Test Parent"
    runs-on: ubuntu-latest
    needs:
      - checkpoint-2
    if: always() && needs.checkpoint-2.outputs.test-parent == 'true'
    outputs:
      status: ${{ job.status }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Run Tests"
        run: |
          npm ci
          npx lerna bootstrap -- --force-local
          cd packages/parent
          npm run test

  confirm-merged-into-staging:
    name: "Confirm Test Results"
    runs-on: ubuntu-latest
    needs:
      - publish_prerelease
      - test-parent
      - checkpoint-2
    if: always()
    steps:
      - name: Check Test Results
        uses: actions/github-script@v6
        with:
          script: |
            const published = "${{ needs.publish_prerelease.outputs.status }}" === "success"
            if (!published) {
              core.setFailed("Publishing pre-release versions of packages must be successful.");
            }
            
            const statuses = {
              "Check Point 1": "${{needs.checkpoint-2.outputs.status}}",
              "parent": "${{needs.test-parent.outputs.status}}",
            };
            console.log(JSON.stringify(statuses, null, 2));
            if(Object.values(statuses).some(status => status === "failure")) {
              core.setFailed("Some of the tests failed.");
            }
