name: Merge Sanity
on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // Get a list of all issues created by the PR opener
            // See: https://octokit.github.io/rest.js/#pagination
#            const response = await github.rest.repos.compareCommitsWithBasehead({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              basehead: "staging...master",
#            });

#            console.log(JSON.stringify(response, null, 2));
            
            console.log(JSON.stringify(context, null, 2));
