name: Merge Sanity
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "Check Merged into Staging"
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context, null, 2));
            
            // Compare feature-branch with staging
            const response = await github.rest.repos.compareCommitsWithBasehead({
              owner: context.repo.owner,
              repo: context.repo.repo,
              basehead: `staging...${context.ref}`,
            });
            const status = response.data.status;
            
            if(status !== "behind") {
              core.setFailed(`Feature-branch '${pull_request.head.ref}' must be merged into 'staging' before merging into 'master'.`);
            }
