name: Suggest
on:
  pull_request:
    types: [ opened ]
    branches:
      - master

jobs:
  suggest-pr-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Suggest Merge into Staging
        uses: actions/github-script@v6
        with:
          script: |
            // Compare feature-branch with staging
            const featureBranch = context.payload.pull_request.head.ref;
            const response = await github.rest.repos.compareCommitsWithBasehead({
              owner: context.repo.owner,
              repo: context.repo.repo,
              basehead: `staging...${featureBranch}`,
            });
            const status = response.data.status;
            
            // Set check status
            if(status !== "behind") {
              const suggestion = `### Suggestion
  
              Create a pull request for \`${featureBranch}\` -> \`staging\` by visiting this link:  [Create Pull Request](${context.payload.repository.url}/pull/new/staging...${featureBranch}).
              `
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: suggestion,
              });
            } 
            
