name: Suggest
on:
  pull_request:
    types: [ opened ]
    branches:
      - master

jobs:
  suggest-pr-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Suggest Merge into Staging
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });
            console.log(JSON.stringify(response, null, 2));