name: Release Flow
on:
  pull_request:
    types: [opened]
    branches:
      - master

jobs:
  suggest-staging-pr:
    name: "Suggest"
    runs-on: ubuntu-latest
    steps:
      - name: Suggest Merge into Staging
        uses: actions/github-script@v6
        with:
          script: |
            // Get PR details
            const thisPull = context.payload.pull_request;
            const thisHead = thisPull.head;
            const featureBranch = thisHead.ref;
            const repo = context.payload.repository.name;
            const owner = context.payload.repository.owner.login;
            
            // Get pulls this-feature-branch -> staging:
            const { data: stagingPulls = [] } = await octokit.rest.pulls.list({
              owner,
              repo,
              state: "all",
              base: "staging",
              head: featureBranch,
              sort: "created",
              per_page: 100,
            });
            
            // Check if PR to staging already exists or already merged
            const stagingPullExists = stagingPulls.some(
              (pull) =>
                pull.head.sha === thisHead.sha &&
                (pull.state === "open" || pull.merged_at != null)
            );
            
            // Make suggestion
            if (!stagingPullExists) {
              const pullRequestURL = `https://github.com/${owner}/${repo}/pull/new/staging...${featureBranch}`;
              const suggestionText = `### Suggestion\n\nYou may want to create a pull request for \`${featureBranch}\` -> \`staging\` by visiting this link:  [Create Pull Request](${pullRequestURL}).`;
            
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: thisPull.number,
                body: suggestionText,
              });
            }
