name: Suggest
on:
  pull_request:
    types: [ opened ]
    branches:
      - master

jobs:
  suggest-pr-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Suggest Merge into Staging
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context, null, 2));
            
            // Compare feature-branch with staging
            const featureBranch = context.payload.pull_request.head.ref;
            const comparison = await github.rest.repos.compareCommitsWithBasehead({
              owner: context.repo.owner,
              repo: context.repo.repo,
              basehead: `staging...${featureBranch}`,
            });
            const status = comparison.data.status;
            
            const pullsToStaging = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              base: "staging",
              head: featureBranch,
            });
            
            // Make suggestion
            if(status !== "behind" && pullsToStaging.data.length === 0) {
              const pullRequestURL = `https://github.com/${context.repo.owner}/${context.repo.repo}/pull/new/staging...${featureBranch}`;
              const suggestion = `### Suggestion\n\nCreate a pull request for \`${featureBranch}\` -> \`staging\` by visiting this link:  [Create Pull Request](${pullRequestURL}).`
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: suggestion,
              });
            }