name: Run Tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Use NodeJS 16"
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: "Setup npm"
        run: |
          npm ci
          npx lerna bootstrap -- --force-local
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: "Run tests"
        run: |
          npx lerna run test
